### ISSUE TITLE
implement global style for static pages

### ISSUE THREAD

**Issue by arikgrahl** [die-offene-gesellschaft/platform#7]
```scss
$red: #d20a11;

// general page stylings
h1, .h1 {
  font-size: 2rem;
  font-weight: bold;
  margin: 3rem 0 2rem;
}
.team h1,
.partner h1,
.contact h1{
    color: $red;
}
h2, .h2 {
  font-size: 1.5rem;
  font-weight: bold;
  margin: 2rem 0 1rem;
}
blockquote {
  margin: 0 0 1rem;
  font-size: 1.2rem;
  color: #555;
  padding: 2rem 0 2rem 2rem;
  font-weight: normal;
  strong{ color: $red; float: right; }
}
ul li {
  margin-bottom: 1rem;
}
footer .copyright,
footer .links a {
  color: grey;
  font-size: 0.8rem;
  font-weight: normal;
}

// about page styling
.about{
    .contact ul li,
    .team ul li{
        h2 {
          margin: 1rem 0;
        }
        p{
          font-size: 0.8rem;
        margin-bottom: 0.3rem;
        }
    }
    .partner h2 {
      font-size: 1.2rem;
    }
}
```
